name: "Python CI"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run tox
        uses: lsst-sqre/run-tox@c8c881a52dfa4e98e55817bac3195df8b0db715c # v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "lint"

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run tox
        uses: lsst-sqre/run-tox@c8c881a52dfa4e98e55817bac3195df8b0db715c # v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "py,coverage-report"
